services:
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: postgres-lighthouse
    ports:
      - "5432:5432"
    environment:
      # superuser account
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    container_name: redis-lighthouse
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  postgres:
  redis:
